version: "3"
services:
  chromedriver:
    image: selenium/standalone-chrome:4.5.2-20221021
    container_name: chromedriver
    environment:
      - SE_NODE_SESSION_TIMEOUT=3600 # 1h
      - SE_NODE_MAX_SESSIONS=3 # Maximum 3 sessions
    ports:
      - "4444:4444"
    healthcheck:
      test: [ "CMD", "curl", "http://localhost:4444" ]
      interval: 1s
      timeout: 3s
      retries: 60

  app:
    image: kcrong/autostudy:latest
    container_name: app
    env_file: .env
    environment:
      - "DRIVER_COMMAND_URL=http://chromedriver:4444"
    depends_on:
      - chromedriver
    restart: always