version: "3"
services:
  chromedriver:
    image: selenium/standalone-chrome:4.5.2-20221021
    container_name: chromedriver
    environment:
      - SE_NODE_SESSION_TIMEOUT=3600 # 1h
      - SE_NODE_MAX_SESSIONS=3 # Maximum 3 sessions
    ports:
      - "4444:4444"

  app:
    image: kcrong/auto-knou:latest
    container_name: app
    env_file: .env
    environment:
      - "DRIVER_COMMAND_URL=https://chromedriver:4444"
